version: '3'
services:
  web:
    build: ./FrontEnd/
    container_name: espacioatemtia-web
    ports: 
      - "80:80"
  api:
    build: ./BackEnd/
    container_name: espacioatemtia-api
    ports: 
      - "5000:80"